theme: jekyll-theme-minimal
title: GeoUnconference #1
description: Resultate der GeoUnconference 1 vom 24.06.2021 / Résultats de la GeoUnconference 1 du 24.06.2021
logo: /assets/logo/png/GeoUnconf_pos_400x260.png
show_downloads: "true"
